apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort      
  selector:
    name: nginx-ingress
    #app: nginx
    #type: front-end    
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      #nodePort: 30025
    - port: 443
      targetPort: 443
      name: https