apiVersion: extensions/v1beta1 #networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-wear
  #annotations:
   # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
 backend:
     serviceName: wear-service
     servicePort: 80
