apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: ec2-34-247-64-16.eu-west-1.compute.amazonaws.com
    http:
      paths:
      - path: /
        backend:
          serviceName: my-service
          servicePort: 80
